#!/usr/bin/env python3
"""Flight Report Generator"""

import sys
from pathlib import Path
from datetime import datetime
from queries.flight_queries import (
    get_parquet_path,
    flight_summary,
    speed_analysis,
    speed_distribution,
    altitude_profile,
    altitude_stats,
    trajectory_sample,
    topic_distribution,
    acceleration_stats,
    validate_parquet,
)


def generate_flight_report(parquet_path, output_path=None):
    if output_path is None:
        output_path = Path(parquet_path).parent / "flight_report.md"

    # Fetch all data
    summary = flight_summary(parquet_path)
    spd_analysis = speed_analysis(parquet_path)
    spd_dist = speed_distribution(parquet_path)
    alt_profile = altitude_profile(parquet_path)
    alt_stats = altitude_stats(parquet_path)
    accel = acceleration_stats(parquet_path)
    topics = topic_distribution(parquet_path)
    validation = validate_parquet(parquet_path)

    # Build report using .values[0] for DataFrames and dict keys for dicts
    report = f"""# Flight Telemetry Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Source:** {parquet_path}
**Samples:** {validation['samples']}
**Total distance:** {validation['total_distance_m']:.1f} m

---
## Flight Summary
| Metric | Value |
|--------|-------|
| Total samples | {int(summary['total_samples'].values[0])} |
| Total distance | {summary['total_distance_m'].values[0]:.1f} m |
| Avg speed | {summary['avg_speed_ms'].values[0]:.2f} m/s |
| Max speed | {summary['max_speed_ms'].values[0]:.2f} m/s |
| Avg altitude | {summary['avg_altitude_m'].values[0]:.1f} m |
| Min altitude | {summary['min_altitude_m'].values[0]:.1f} m |
| Max altitude | {summary['max_altitude_m'].values[0]:.1f} m |

---
## Altitude Profile
| Range | Count | Avg Speed | Avg Step |
|-------|-------|-----------|----------|
"""
    for _, row in alt_profile.iterrows():
        report += f"| {row['altitude_range']} | {int(row['count'])} | {row['avg_speed']:.2f} | {row['avg_step_m']:.2f} |\n"

    report += f"""
---
## Speed Analysis
| Speed Range | Count | Pct |
|------------|-------|-----|
"""
    for _, row in spd_dist.iterrows():
        report += f"| {row['speed_range']} | {int(row['count'])} | {row['pct']}% |\n"

    report += f"""
---
## Acceleration
| Avg X | Avg Y | Avg Z | Max |
|-------|-------|-------|-----|
| {accel['avg_ax'].values[0]:.3f} m/s² | {accel['avg_ay'].values[0]:.3f} m/s² | {accel['avg_az'].values[0]:.3f} m/s² | {accel['max_accel'].values[0]:.3f} m/s² |

---
## Topic Distribution
| Topic | Type | Count | Pct |
|-------|------|-------|-----|
"""
    for _, row in topics.iterrows():
        report += f"| {row['topic']} | {row['msg_type']} | {int(row['count'])} | {row['pct']}% |\n"

    report += "\n---\n*Generated by ROS 2 Swarm Pipeline*\n"

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(report)

    print(f"[REPORT] Generated: {output_path}")
    return report


def main():
    try:
        parquet_path = get_parquet_path()
    except FileNotFoundError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    output_path = Path(parquet_path).parent / "flight_report.md"
    generate_flight_report(parquet_path, output_path)
    return 0


if __name__ == "__main__":
    exit(main())